***JUAN CARLOS DAMIAN DIAZ***

In [13]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [14]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [15]:
ConjDatReg = pd.read_csv('/content/gdrive/MyDrive/DataSet1.csv')
ConjDatReg

<ipython-input-15-70ecda6d6db5>:1: DtypeWarning: Columns (47,73) have mixed types. Specify dtype option on import or set low_memory=False.
  ConjDatReg = pd.read_csv('/content/gdrive/MyDrive/DataSet1.csv')

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,...,R_PHAEO,R_PRES,R_SAMP,DIC1,DIC2,TA1,TA2,pH2,pH1,DIC Quality Comment
0,1,1,054.0 056.0,19-4903CR-HY-060-0930-05400560-0000A-3,0,10.500,33.4400,NaN,25.64900,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,054.0 056.0,19-4903CR-HY-060-0930-05400560-0008A-3,8,10.460,33.4400,NaN,25.65600,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,054.0 056.0,19-4903CR-HY-060-0930-05400560-0010A-7,10,10.460,33.4370,NaN,25.65400,NaN,...,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,054.0 056.0,19-4903CR-HY-060-0930-05400560-0019A-3,19,10.450,33.4200,NaN,25.64300,NaN,...,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,054.0 056.0,19-4903CR-HY-060-0930-05400560-0020A-7,20,10.450,33.4210,NaN,25.64300,NaN,...,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
864858,34404,864859,093.4 026.4,20-1611SR-MX-310-2239-09340264-0000A-7,0,18.744,33.4083,5.805,23.87055,108.74,...,0.18,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864859,34404,864860,093.4 026.4,20-1611SR-MX-310-2239-09340264-0002A-3,2,18.744,33.4083,5.805,23.87072,108.74,...,0.18,2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864860,34404,864861,093.4 026.4,20-1611SR-MX-310-2239-09340264-0005A-3,5,18.692,33.4150,5.796,23.88911,108.46,...,0.18,5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864861,34404,864862,093.4 026.4,20-1611SR-MX-310-2239-09340264-0010A-3,10,18.161,33.4062,5.816,24.01426,107.74,...,0.31,10,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864862,34404,864863,093.4 026.4,20-1611SR-MX-310-2239-09340264-0015A-3,15,17.533,33.3880,5.774,24.15297,105.66,...,0.61,15,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
ConjDatClas = pd.read_csv('/content/gdrive/MyDrive/data.csv')
ConjDatClas

,Age,Duration,Frequency,Location,Character,Intensity,Nausea,Vomit,Phonophobia,Photophobia,...,Vertigo,Tinnitus,Hypoacusis,Diplopia,Defect,Ataxia,Conscience,Paresthesia,DPF,Type
0,30,1,5,1,1,2,1,0,1,1,...,0,0,0,0,0,0,0,0,0,Typical aura with migraine
1,50,3,5,1,1,3,1,1,1,1,...,1,0,0,0,0,0,0,0,0,Typical aura with migraine
2,53,2,1,1,1,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,Typical aura with migraine
3,45,3,5,1,1,3,1,0,1,1,...,1,0,0,0,0,0,0,0,0,Typical aura with migraine
4,53,1,1,1,1,2,1,0,1,1,...,0,0,0,0,0,0,0,0,1,Typical aura with migraine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,39,1,1,1,1,3,1,1,1,1,...,1,0,0,1,0,0,0,0,1,Basilar-type aura
396,20,3,2,1,1,3,1,0,1,1,...,0,1,1,0,0,0,0,0,1,Basilar-type aura
397,28,3,2,1,1,3,1,0,1,1,...,1,0,0,0,1,0,0,0,1,Basilar-type aura
398,20,3,1,1,1,3,1,0,1,1,...,1,0,0,0,0,0,0,1,1,Basilar-type aura
399,37,1,1,1,1,3,1,1,1,1,...,1,0,0,0,0,0,1,0,1,Basilar-type aura

In [17]:
print(ConjDatReg.columns)
print(ConjDatClas.columns)

Index(['Cst_Cnt', 'Btl_Cnt', 'Sta_ID', 'Depth_ID', 'Depthm', 'T_degC',
       'Salnty', 'O2ml_L', 'STheta', 'O2Sat', 'Oxy_µmol/Kg', 'BtlNum',
       'RecInd', 'T_prec', 'T_qual', 'S_prec', 'S_qual', 'P_qual', 'O_qual',
       'SThtaq', 'O2Satq', 'ChlorA', 'Chlqua', 'Phaeop', 'Phaqua', 'PO4uM',
       'PO4q', 'SiO3uM', 'SiO3qu', 'NO2uM', 'NO2q', 'NO3uM', 'NO3q', 'NH3uM',
       'NH3q', 'C14As1', 'C14A1p', 'C14A1q', 'C14As2', 'C14A2p', 'C14A2q',
       'DarkAs', 'DarkAp', 'DarkAq', 'MeanAs', 'MeanAp', 'MeanAq', 'IncTim',
       'LightP', 'R_Depth', 'R_TEMP', 'R_POTEMP', 'R_SALINITY', 'R_SIGMA',
       'R_SVA', 'R_DYNHT', 'R_O2', 'R_O2Sat', 'R_SIO3', 'R_PO4', 'R_NO3',
       'R_NO2', 'R_NH4', 'R_CHLA', 'R_PHAEO', 'R_PRES', 'R_SAMP', 'DIC1',
       'DIC2', 'TA1', 'TA2', 'pH2', 'pH1', 'DIC Quality Comment'],
      dtype='object')
Index(['Age', 'Duration', 'Frequency', 'Location', 'Character', 'Intensity',
       'Nausea', 'Vomit', 'Phonophobia', 'Photophobia', 'Visual', 'Sensory',
       'Dysphasia', 'Dysarthria', 'Vertigo', 'Tinnitus', 'Hypoacusis',
       'Diplopia', 'Defect', 'Ataxia', 'Conscience', 'Paresthesia', 'DPF',
       'Type'],
      dtype='object')

In [18]:

# Unir los dos DataFrames 
#ConjDatReg = ConjDatReg.rename(columns={'T_degC': 'Intensity', 'Salnty': 'Location'})
data = pd.concat([ConjDatClas, ConjDatReg], axis=1)
# guardar el data frame fusionado en un archivo csv
data.to_csv('merged_data.csv', index=False)
print(data.head())

    Age  Duration  Frequency  Location  Character  Intensity  Nausea  Vomit  \
0  30.0       1.0        5.0       1.0        1.0        2.0     1.0    0.0
1  50.0       3.0        5.0       1.0        1.0        3.0     1.0    1.0
2  53.0       2.0        1.0       1.0        1.0        2.0     1.0    1.0
3  45.0       3.0        5.0       1.0        1.0        3.0     1.0    0.0
4  53.0       1.0        1.0       1.0        1.0        2.0     1.0    0.0

   Phonophobia  Photophobia  ...  R_PHAEO  R_PRES  R_SAMP  DIC1  DIC2  TA1  \
0          1.0          1.0  ...      NaN       0     NaN   NaN   NaN  NaN
1          1.0          1.0  ...      NaN       8     NaN   NaN   NaN  NaN
2          1.0          1.0  ...      NaN      10     NaN   NaN   NaN  NaN
3          1.0          1.0  ...      NaN      19     NaN   NaN   NaN  NaN
4          1.0          1.0  ...      NaN      20     NaN   NaN   NaN  NaN

   TA2  pH2  pH1  DIC Quality Comment
0  NaN  NaN  NaN                  NaN
1  NaN  NaN  NaN                  NaN
2  NaN  NaN  NaN                  NaN
3  NaN  NaN  NaN                  NaN
4  NaN  NaN  NaN                  NaN

[5 rows x 98 columns]

***1.Modelo de regresión.***

In [19]:
# Seleccionar las variables predictoras y la variable objetivo
X = ConjDatReg[['Salnty', 'Depthm']].fillna(0) # Rellenar los valores faltantes con 0
y = ConjDatReg['T_degC'].fillna(0)



# Descripción del algoritmo y suposiciones
"""
El algoritmo de regresión lineal múltiple se utiliza para modelar la relación entre una variable 
dependiente y dos o más variables independientes. Supone que la relación es lineal, es decir, que 
los cambios en las variables predictoras tienen una relación lineal con la variable objetivo. El 
modelo también asume que no hay multicolinealidad entre las variables predictoras y que los errores 
del modelo son independientes y se distribuyen normalmente.
"""


# Dividir los datos en conjuntos de entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Importar el algoritmo de regresión lineal múltiple
from sklearn.linear_model import LinearRegression

# Crear una instancia del modelo de regresión lineal múltiple
model = LinearRegression()

# Realizar validación cruzada de 5 veces
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X_train, y_train, cv=5)

# Imprimir la puntuación de validación cruzada media y la desviación estándar, Coeficiente de determinación R^2, Error absoluto medio (MAE), Error cuadrático medio (MSE)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print('')
print("Puntuaciones de validación cruzada:", scores)
print("Media de las puntuaciones de validación cruzada:", scores.mean())
print("Desviación estándar de las puntuaciones de validación cruzada:", scores.std())

# Explicación de por qué la validación cruzada es importante para evaluar el rendimiento del modelo
"""
La validación cruzada es importante para evaluar el rendimiento del modelo porque proporciona una 
medida más precisa del rendimiento del modelo que la división de los datos en conjuntos de entrenamiento 
y prueba. La validación cruzada divide los datos en múltiples conjuntos de entrenamiento y prueba, 
permitiendo que el modelo se ajuste y se evalúe con todos los datos disponibles. Esto ayuda a 
evitar problemas como el sobreajuste y proporciona una estimación más precisa del rendimiento del 
modelo en datos nuevos y no vistos.
"""



# Definir la cuadrícula de parámetros a explorar
param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'positive': [True, False]
}

# Realizar la búsqueda en malla de los hiperparámetros óptimos
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(X_train, y_train)


#Informa los mejores hiperparámetros que encontró y la puntuación de validación cruzadacorrespondiente.
"""
Se utilizó la búsqueda en malla para ajustar los hiperparámetros, y se consideró un rango de valores de True y False para ambos parámetros.
Se optó por esto porque no se tenía información previa sobre la necesidad de ajustar una intercepción o normalizar los datos,
y se quería explorar todas las opciones posibles.
"""



# Mejores hiperparámetros y puntuación de validación cruzada correspondiente
print("Mejores hiperparámetros:", grid_search.best_params_)
print("Puntuación de validación cruzada correspondiente:", grid_search.best_score_)

# Crear modelo base
model = LinearRegression()

# Ajustar modelo base
model.fit(X_train, y_train)

# Crear modelo ajustado y ajustarlo
best_model = LinearRegression(fit_intercept=True, positive=True)
best_model.fit(X_train, y_train)

# Realizar predicciones en los datos de prueba
y_pred_best = best_model.predict(X_test)
y_pred_base = model.predict(X_test)

# Evaluar y comparacion del rendimiento de los modelos
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print('')
print("Modelo de regresión ajustado:")
print('Coeficiente de determinación R^2:', r2_score(y_test, y_pred_best))
print('Error absoluto medio (MAE):', mean_absolute_error(y_test, y_pred_best))
print('Error cuadrático medio (MSE):', mean_squared_error(y_test, y_pred_best))

print('')
print('Modelo base:')
print('')
print('Coeficiente de determinación R^2:', r2_score(y_test, y_pred_base))
print('Error absoluto medio (MAE):', mean_absolute_error(y_test, y_pred_base))
print('Error cuadrático medio (MSE):', mean_squared_error(y_test, y_pred_base))

Puntuaciones de validación cruzada: [0.4217944  0.41441162 0.41621394 0.42159095 0.41783323]
Media de las puntuaciones de validación cruzada: 0.4183688294010469
Desviación estándar de las puntuaciones de validación cruzada: 0.0029225519056235716
Mejores hiperparámetros: {'copy_X': True, 'fit_intercept': True, 'positive': False}
Puntuación de validación cruzada correspondiente: 0.4183688294010469

Modelo de regresión ajustado:
Coeficiente de determinación R^2: 0.015255177239070217
Error absoluto medio (MAE): 3.5538537235148056
Error cuadrático medio (MSE): 18.97509465524751

Modelo base:

Coeficiente de determinación R^2: 0.41468060266441564
Error absoluto medio (MAE): 2.526475207431553
Error cuadrático medio (MSE): 11.278547204600542

***JUAN CARLOS DAMIAN DIAZ***

***2.Modelo de clasificación***

In [20]:
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# Cargar los datos del archivo CSV
ConjDatClas = pd.read_csv('/content/gdrive/MyDrive/data.csv')

# Seleccionar las características (columnas) y la variable objetivo (target)
features = ['Age', 'Duration', 'Frequency', 'Location', 'Character', 'Intensity']
target = 'Defect'

X = ConjDatClas[features]
y = ConjDatClas[target]

# Convertir las columnas que tienen tipos mixtos a float
X = X.apply(pd.to_numeric, errors='coerce')

# Eliminar las filas con valores faltantes
X = X.dropna()
y = y[X.index]

# Crear un clasificador de árbol de decisión
clf = DecisionTreeClassifier()

# Realizar una validación cruzada de 5 veces y obtener las puntuaciones de validación cruzada
scores = cross_val_score(clf, X, y, cv=5)

# Explicar por qué la validación cruzada es importante para evaluar el rendimiento de tu modelo.
"""
La validación cruzada es importante para evaluar el rendimiento de un modelo porque permite estimar el rendimiento del modelo en datos no vistos y ayuda a evitar el sobreajuste del modelo a los datos de entrenamiento.

En lugar de simplemente dividir los datos en conjuntos de entrenamiento y prueba y ajustar el modelo a los datos de entrenamiento, la validación cruzada implica dividir los datos en múltiples subconjuntos de entrenamiento y prueba, ajustar y evaluar el modelo en cada uno de ellos, y luego tomar la media de las puntuaciones de evaluación como una medida del rendimiento del modelo.

La validación cruzada también permite ajustar los parámetros del modelo y seleccionar el mejor modelo para los datos mediante la comparación de las puntuaciones de evaluación de los modelos ajustados.
"""

# Imprimir la media y la desviación estándar de las puntuaciones de validación cruzada
print('Puntuaciones de validación cruzada: {}'.format(scores))
print("Media de las puntuaciones de validación cruzada:", np.mean(scores))
print("Desviación estándar de las puntuaciones de validación cruzada:", np.std(scores))

param_grid = {'max_depth': [5, 10, 20],
              'max_features': [5, 10, 20],
              'min_samples_leaf': [1, 5, 10],
              'min_samples_split': [2, 5, 10]}

# Definir métricas de evaluación
scoring = {'accuracy': make_scorer(accuracy_score)}

# Realizar la búsqueda en cuadrícula
grid_search = GridSearchCV(clf, param_grid=param_grid, scoring=scoring, refit='accuracy', cv=5, n_jobs=-1)
grid_search.fit(X, y)
#

"""

El objetivo de ajustar los hiperparámetros es encontrar la combinación óptima de valores que maximice el rendimiento del modelo. 
En este caso, los hiperparámetros que se ajustaron son 'max_depth', 'max_features', 'min_samples_leaf'
y 'min_samples_split'.El rango de valores considerados para cada hiperparámetro determina cuántas opciones diferentes se evaluarán
 para cada hiperparámetro durante la búsqueda en cuadrícula. Por ejemplo, para 'max_depth', se consideraron los valores 5, 10 y 20. 
 Esto significa que el modelo se ajustará y evaluará con cada uno de estos valores, y luego se seleccionará el que dé la mejor puntuación.

"""

# Imprimir los mejores hiperparámetros y la puntuación promedio de validación cruzada
print('Mejores hiperparámetros encontrados:')
print(grid_search.best_params_)
print('Puntuación de validación cruzada media:')
print(grid_search.cv_results_['mean_test_accuracy'])

Puntuaciones de validación cruzada: [0.9625 0.9875 0.9875 0.9625 0.975 ]
Media de las puntuaciones de validación cruzada: 0.975
Desviación estándar de las puntuaciones de validación cruzada: 0.011180339887498959
Mejores hiperparámetros encontrados:
{'max_depth': 5, 'max_features': 5, 'min_samples_leaf': 1, 'min_samples_split': 10}
Puntuación de validación cruzada media:
[0.9825 0.98   0.985  0.985  0.985  0.985  0.985  0.985  0.985  0.9825
 0.9825 0.985  0.985  0.985  0.985  0.985  0.985  0.985  0.9825 0.98
 0.985  0.985  0.985  0.985  0.985  0.985  0.985  0.975  0.9775 0.985
 0.985  0.985  0.985  0.985  0.985  0.985  0.975  0.9775 0.985  0.985
 0.985  0.985  0.985  0.985  0.985  0.975  0.9775 0.985  0.985  0.985
 0.985  0.985  0.985  0.985  0.9725 0.9825 0.985  0.985  0.985  0.985
 0.985  0.985  0.985  0.975  0.98   0.985  0.985  0.985  0.985  0.985
 0.985  0.985  0.975  0.98   0.985  0.985  0.985  0.985  0.985  0.985
 0.985 ]

In [21]:
# Crear un clasificador de árbol de decisión sin ajuste de hiperparámetros
clf_base = DecisionTreeClassifier()

# Realizar una validación cruzada de 5 veces y obtener las puntuaciones de validación cruzada
scores_base = cross_val_score(clf_base, X, y, cv=5)

print('')

# Imprimir y comparar la media y la desviación estándar de las puntuaciones de validación cruzada para el modelo base y modelo ajustado
print('Puntuaciones de validación cruzada para el modelo base: {}'.format(scores_base))
print("Media de las puntuaciones de validación cruzada para el modelo base:", np.mean(scores_base))
print("Desviación estándar de las puntuaciones de validación cruzada para el modelo base:", np.std(scores_base))
print("Media de las puntuaciones de validación cruzada para el modelo base:", np.mean(scores_base))
print('')

print("Media de las puntuaciones de validación cruzada para el modelo ajustado:", grid_search.best_score_)
print("Media de las puntuaciones de validación cruzada para el modelo ajustado:", np.mean(scores))
print("Desviación estándar de las puntuaciones de validación cruzada para el modelo ajustado:", np.std(scores))

Puntuaciones de validación cruzada para el modelo base: [0.95   0.9875 0.9875 0.9625 0.975 ]
Media de las puntuaciones de validación cruzada para el modelo base: 0.9724999999999999
Desviación estándar de las puntuaciones de validación cruzada para el modelo base: 0.01457737973711328
Media de las puntuaciones de validación cruzada para el modelo base: 0.9724999999999999

Media de las puntuaciones de validación cruzada para el modelo ajustado: 0.985
Media de las puntuaciones de validación cruzada para el modelo ajustado: 0.975
Desviación estándar de las puntuaciones de validación cruzada para el modelo ajustado: 0.011180339887498959